#!/bin/sh
ROOTDIR=$HOME/.bin/erlang
BINDIR=$ROOTDIR/erts-10.2.3/bin
EMU=beam
PROGNAME=`echo $0 | sed 's/.*\///'`
export EMU
export ROOTDIR
export BINDIR
export PROGNAME
exec "$BINDIR/erlexec" ${1+"$@"}
