CREATE table ORDER_DATA(ORDER_ID BIGINT(19) NOT NULL,CUSTOMERID BIGINT(19),IS_COD BOOLEAN(1),ORDER_CREATED_ON BIGINT(19),ORDER_STATUS VARCHAR(255) ,PAYMENT_CHANNEL VARCHAR(255),SHIPPING_ADDRESS VARCHAR(255),TOTAL_AMOUNT DOUBLE(17));

CREATE table ORDER_LINE_ITEM(ORDER_LINE_ITEM_ID BIGINT(19) NOT NULL,ITEM_QTY INTEGER(10) NOT NULL,ORDER_ID BIGINT(19),SKU_ID BIGINT(19));